language: python
python:
#  - 2.6 failed webtest lib
  - 2.7
#  - 3.2 failed coverage lib
  - 3.3
  - 3.4
  - 3.5
  - pypy

install:
  - pip install webtest
  - pip install codecov
  - pip install bottle
  - python${PY:-} setup.py develop

script:
  - coverage run -a test/test_bottle_integration.py 
  - coverage run -a test/test_create_and_decode_token.py

after_success:
  - codecov
